src/crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


admin.site.site_title = "Galette CRM"
admin.site.site_header = "Galette CRM"

urlpatterns = [
    path("", RedirectView.as_view(permanent=False, url="erad/")),
    path("erad/", include("erad.urls")),
    path("work/", include("work.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("data_management/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__", include(
        debug_toolbar.urls))] + urlpatterns

src/erad/urls.py
from django.urls import path

from erad import views

app_name = "erad"
urlpatterns = [
    path("", views.ResearcherFrontView.as_view(), name="front"),
    path("list", views.ResearcherListView.as_view(), name="list"),
    path("detail/<str:pk>/", views.ResearcherDetailView.as_view(), name="detail"),
]

src/work/urls.py
from django.urls import path

from . import views

app_name = "work"
urlpatterns = [
    path("", views.KeywordFrontView.as_view(), name="front"),
    path("list", views.KeywordListView.as_view(), name="list"),
    path("detail/<int:pk>/", views.KeywordDetailView.as_view(), name="detail"),
]

src/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Galette CRM</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous" />
    <!-- Favicons -->
    <link rel="icon" href="{% static 'favicon.ico' %}" />
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
</head>

<body>
    <div
        class="sticky-top d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal"><a class="p-2 text-dark" href="{% url 'erad:front' %}">Galette
                CRM</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'erad:front' %}">研究者検索</a>
            <a class="p-2 text-dark" href="{% url 'work:front' %}">研究キーワード検索</a>
            <a class="p-2 text-dark" href="{% url 'admin:index' %}">データ管理</a>
        </nav>
        <a class="btn btn-outline-info btn-sm" href="{% url 'logout' %}">ログアウト（{{ user.get_username }}）</a>
    </div>

    <div class="container">
        <div class="row">
            <main role="main" class="col">
                {% if messages %}
                <div class="alert alert-success alert-dismissible fade show my-4" role="alert">
                    {% for message in messages %}
                    {{ message }}
                    {% endfor %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
                <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h3">{% block header %}{% endblock header %}</h1>
                </div>
                {% block contents %} {% endblock contents %}
            </main>
        </div>
    </div>
    <footer class="footer sticky-bottom">
        <div class="container-fluid p-5 bg-light">
            <div class="row">
                <div class="col-md-12">
                    <a class="text-muted h5" href="{% url 'erad:front' %}">Galette CRM</a>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/about.html
{% extends "_base.html" %}
{% load static %}

{% block header %}Galette CRMについて{% endblock header %}

{% block contents %}
<div class="row">
    <div class="col-md-6">
    </div>
</div>

{% endblock contents %}