src/crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


admin.site.site_title = "Galette CRM"
admin.site.site_header = "Galette CRM"

urlpatterns = [
    path("", RedirectView.as_view(permanent=False, url="erad/")),
    path("erad/", include("erad.urls")),
    path("work/", include("work.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("data_management/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__", include(
        debug_toolbar.urls))] + urlpatterns

src/erad/urls.py
from django.urls import path

from erad import views

app_name = "erad"
urlpatterns = [
    path("", views.ResearcherFrontView.as_view(), name="front"),
    path("list", views.ResearcherListView.as_view(), name="list"),
    path("detail/<str:pk>/", views.ResearcherDetailView.as_view(), name="detail"),
]

src/work/urls.py
from django.urls import path

from . import views

app_name = "work"
urlpatterns = [
    path("", views.KeywordFrontView.as_view(), name="front"),
    path("list", views.KeywordListView.as_view(), name="list"),
    path("detail/<int:pk>/", views.KeywordDetailView.as_view(), name="detail"),
]

src/erad/models.py
from datetime import date

from django.db import models


class Researcher(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "e-Rad研究者データ"

    eradcode = models.CharField("研究者番号", max_length=8, primary_key=True)
    kenkyuushashimei_sei = models.CharField("研究者氏名-姓", max_length=50)
    kenkyuushashimei_mei = models.CharField("研究者氏名-名", max_length=50)
    furigana_sei = models.CharField("フリガナ-姓", max_length=50)
    furigana_mei = models.CharField("フリガナ-名", max_length=50)
    tsuushoumei_sei = models.CharField(
        "通称名-姓", max_length=50,  blank=True, null=True)
    tsuushoumei_mei = models.CharField(
        "通称名-名", max_length=50,  blank=True, null=True)
    tsuushoumeifurigana_sei = models.CharField(
        "通称名フリガナ-姓", max_length=50,  blank=True, null=True)
    tsuushoumeifurigana_mei = models.CharField(
        "通称名フリガナ-名", max_length=50,  blank=True, null=True)
    eiji_sei = models.CharField("英字-姓", max_length=50, blank=True, null=True)
    eiji_mei = models.CharField("英字-名", max_length=50, blank=True, null=True)
    seinengappi = models.DateField("生年月日", blank=True, null=True)
    SEX_CHOICES = (("0", ""), ("1", "男性"), ("2", "女性"), ("9", "その他"))
    seibetsu = models.CharField("性別", choices=SEX_CHOICES, max_length=1)
    gakui = models.CharField("学位", max_length=50,  blank=True, null=True)
    gakuishutokunengappi = models.CharField(
        "学位取得年月日", max_length=50, blank=True, null=True)
    bukyokumei = models.CharField("部局名", max_length=50)
    shokumei = models.CharField("職位", max_length=50)
    mailaddress1 = models.EmailField("メールアドレス1", blank=True, null=True)
    mailaddress2 = models.EmailField("メールアドレス2", blank=True, null=True)
    kakenhiouboshikaku = models.CharField("科研費応募資格", max_length=1)
    shutarukenkyuukikan = models.CharField("主たる研究機関", max_length=1)
    bukyokuchakuninbi = models.DateField("部局着任日", blank=True, null=True)
    bukyokutaininbi = models.DateField("部局退任日", blank=True, null=True)
    # 各種氏名を連結したフルネーム
    kanjishimei = models.CharField("研究者氏名", max_length=100)
    kanashimei = models.CharField("フリガナ", max_length=100)
    tsuushoumei = models.CharField(
        "通称名", max_length=100,  blank=True, null=True)
    tsuushoumei_kana = models.CharField(
        "通称名フリガナ", max_length=50,  blank=True, null=True)
    eijishimei = models.CharField(
        "英字氏名", max_length=100, blank=True, null=True)

    def age(self):
        today = date.today()
        age = today.year - self.seinengappi.year
        if (today.month, today.day) < (self.seinengappi.month, self.seinengappi.day):
            age -= 1
        return age

    def __str__(self):
        return self.eradcode


class Application(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "e-Rad応募データ"
    kakushu_no = models.CharField("各種No", max_length=20)
    kadai_id = models.CharField("課題ID", max_length=20)
    oubo_saitaku_bangou = models.CharField("応募／採択番号", max_length=20)
    nendo = models.IntegerField("年度")
    seido_code = models.CharField("制度コード", max_length=7)
    seidomei = models.CharField("制度名", max_length=200)
    jigyoumei = models.CharField("事業名", max_length=200)
    koubogroupmei = models.CharField("公募グループ名", max_length=200)
    koubo_nendo = models.IntegerField("公募年度")
    koubomei = models.CharField("公募名", max_length=200)
    kadaimei = models.CharField("研究開発課題名", max_length=200)
    kaishi_nendo = models.IntegerField("研究期間開始年度")
    shuuryou_nendo = models.IntegerField("研究期間終了年度")
    STATUS_CHOICE = (("1", "応募中"), ("2", "応募済"), ("3", "審査中"), ("4", "審査済"),
                     ("5", "採択"), ("6", "不受理"), ("7", "取下げ"),
                     ("8", "不採択（足切り）"), ("9", "不採択"))
    status = models.CharField("ステータス", max_length=1, choices=STATUS_CHOICE)
    eradcode = models.CharField("研究者番号", max_length=8)
    shimeikanji_sei = models.CharField("氏名漢字（姓）", max_length=50)
    shimeikanji_mei = models.CharField("氏名漢字（名）", max_length=50)
    kenkyuukikanmei = models.CharField("研究機関名", max_length=50)
    bukyokumei = models.CharField("部局名", max_length=50, blank=True, null=True)
    yakushoku = models.CharField("役職", max_length=50, blank=True, null=True)

    def __str__(self):
        return self.kakushu_no

src/work/models.py
from django.db import models


class Keyword(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "キーワード"
    # keyword_id = models.IntegerField("キーワードID", primary_key=True)
    keyword = models.CharField("キーワード", max_length=255)
    researcher_count = models.IntegerField("使用研究者数")
    cumcount = models.IntegerField("のべ使用回数")

    def __str__(self):
        return self.keyword


class Work(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "研究課題"
    awardnumber = models.CharField("課題番号", max_length=255)
    title = models.CharField("課題名", max_length=255)
    startfiscalyear = models.IntegerField("研究開始年度")
    role = models.CharField("役割", max_length=255)
    category_name = models.CharField("研究種目", max_length=255)
    eradcode = models.CharField("研究者番号", max_length=8)
    fullname = models.CharField("氏名", max_length=255)
    institution = models.CharField("部局名", max_length=255)
    department = models.CharField("部局名", max_length=255)
    jobtitle = models.CharField("職名", max_length=255)
    keywords = models.ManyToManyField(Keyword)

    def __str__(self):
        return self.eradcode

src/work/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django import forms
from django.urls import reverse


class KeywordSearchForm(forms.Form):
    q = forms.CharField(label="キーワード", required=False)

    def __init__(self, *args, **kwargs):
        super(KeywordSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('q', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
        )
        self.helper.form_method = "GET"
        self.helper.form_action = reverse("work:list")
        self.helper.add_input(
            Submit('', '検索', css_class='btn btn-primary'))

src/work/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.views.generic import DetailView, ListView

from .forms import KeywordSearchForm
from .models import Keyword, Work


class KeywordFrontView(LoginRequiredMixin, ListView):
    paginate_by = 100
    template_name = "work/keyword_front.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = KeywordSearchForm()
        return context

    def get_queryset(self):
        queryset = Keyword.objects.all().order_by("-researcher_count", "-cumcount")
        return queryset


class KeywordListView(LoginRequiredMixin, ListView):
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["q"] = self.request.GET.get("q")
        return context

    def get_queryset(self):
        queryset = Keyword.objects.all()
        if self.request.GET.get("q"):
            # 検索クエリ内の空白文字を削除する
            q = self.request.GET.get("q").strip()
            table = str.maketrans({"　": "", " ": ""})
            q = q.translate(table)
            # 検索する
            queryset = queryset.filter(keyword__icontains=q)
        queryset = queryset.order_by(
            "-researcher_count", "-cumcount", "keyword")
        return queryset


class KeywordDetailView(LoginRequiredMixin, DetailView):
    model = Keyword

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        context["work_list"] = self.object.work_set.all().order_by(
            "-startfiscalyear")
        context["researcher_list"] = Work.objects.prefetch_related().filter(keywords__id=pk).values(
            "eradcode", "fullname").annotate(total=Count("eradcode")).order_by("-total")
        return context

src/work/templates/work/keyword_detail.html
{% extends "_base.html" %}
{% load static %}
{% load humanize %}
{% block header %}キーワード詳細{% endblock header %}

{% block contents %}
<div class="row">
    <div class="col-md-12">
        <h3>{{ object.keyword }}</h3>
        <hr>
        <h3 class="h5">関連研究者</h3>
        {% for researcher in researcher_list %}
        <a class="btn btn-outline-secondary btn-sm my-1" href="{% url 'erad:detail' researcher.eradcode %}">
            {{ researcher.fullname }}
            <span class="badge badge-pill badge-light">{{ researcher.total }}</span>
        </a>
        {% endfor %}
        <hr>
        <h3 class="h5">研究課題</h3>
        <table class="table table-striped table-sm">
            <thead class="thead-light">
                <tr>
                    <th width=10%>氏名</th>
                    <th width=15%>研究種目</th>
                    <th width=15%>役割</th>
                    <th width=10%>研究開始年度</th>
                    <th width=50%>研究課題名</th>
                </tr>
            </thead>
            <tbody>
                {% for work in work_list %}
                <tr>
                    <td><a href="{% url 'erad:detail' work.eradcode %}">{{ work.fullname }}</a></td>
                    <td>{{ work.category_name }}</td>
                    <td>{{ work.role }}</td>
                    <td>{{ work.startfiscalyear }}</td>
                    <td><a href="https://kaken.nii.ac.jp/search/?qb={{ work.awardnumber }}" target="_blank">
                            {{ work.title }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>



{% endblock contents%}

src/work/templates/work/keyword_front.html
{% extends "_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block header %}研究キーワード検索{% endblock header %}

{% block contents %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                {% crispy search_form search_form.helper %}
            </div>
        </div>
    </div>
</div>

<div class="row my-5">
    <div class="col-md-12">
        <h3>使用回数の多いキーワードから探す</h3>
        {% if object_list %}
        <div class="table-responsive">
            <table class="table table-sm table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>キーワード</th>
                        <th>
                            <div class="text-center">使用研究者数</div>
                        </th>
                        <th>
                            <div class="text-center">のべ使用回数</div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td><a href="{% url 'work:detail' object.pk %}">{{ object.keyword }}</a></td>
                        <td>
                            <div class="text-center">{{ object.researcher_count }}</div>
                        </td>
                        <td>
                            <div class="text-center">{{ object.cumcount }}</div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {% else %}
        <p class="my-5">見つかりませんでした。</p>
        {% endif %}

    </div>
</div>

{% endblock contents %}

src/work/templates/work/keyword_list.html
{% extends "_base.html" %}
{% load static %}
{% load humanize %}
{% block header %}キーワード検索 結果{% endblock header %}


{% block contents %}

{% if object_list %}
<div class="alert alert-primary my-3">
    検索結果：<span class="h3">{{ paginator.count | intcomma }}</span> 件（検索語：{{ q }}）
</div>
<div class="table-responsive">
    <table class="table table-sm table-hover">
        <thead class="thead-light">
            <tr>
                <th>キーワード</th>
                <th>該当研究者数</th>
                <th>のべ使用回数</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.keyword }}</td>
                <td>{{ object.researcher_count }}</a></td>
                <td>{{ object.cumcount }}</td>
                <td>
                    <a href="{% url 'work:detail' object.pk %}" class="btn btn-outline-primary btn-sm" role="button"
                        data-bs-toggle="button">詳細</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p class="my-5">見つかりませんでした。</p>
{% endif %}



{% endblock contents %}