src/crm/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView


admin.site.site_title = "Galette CRM"
admin.site.site_header = "Galette CRM"

urlpatterns = [
    path("", RedirectView.as_view(permanent=False, url="erad/")),
    path("erad/", include("erad.urls")),
    path("work/", include("work.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("data_management/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__", include(
        debug_toolbar.urls))] + urlpatterns

src/erad/urls.py
from django.urls import path

from erad import views

app_name = "erad"
urlpatterns = [
    path("", views.ResearcherFrontView.as_view(), name="front"),
    path("list", views.ResearcherListView.as_view(), name="list"),
    path("detail/<str:pk>/", views.ResearcherDetailView.as_view(), name="detail"),
]

src/work/urls.py
from django.urls import path

from . import views

app_name = "work"
urlpatterns = [
    path("", views.KeywordFrontView.as_view(), name="front"),
    path("list", views.KeywordListView.as_view(), name="list"),
    path("detail/<int:pk>/", views.KeywordDetailView.as_view(), name="detail"),
]

src/erad/models.py
from datetime import date

from django.db import models


class Researcher(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "e-Rad研究者データ"

    eradcode = models.CharField("研究者番号", max_length=8, primary_key=True)
    kenkyuushashimei_sei = models.CharField("研究者氏名-姓", max_length=50)
    kenkyuushashimei_mei = models.CharField("研究者氏名-名", max_length=50)
    furigana_sei = models.CharField("フリガナ-姓", max_length=50)
    furigana_mei = models.CharField("フリガナ-名", max_length=50)
    tsuushoumei_sei = models.CharField(
        "通称名-姓", max_length=50,  blank=True, null=True)
    tsuushoumei_mei = models.CharField(
        "通称名-名", max_length=50,  blank=True, null=True)
    tsuushoumeifurigana_sei = models.CharField(
        "通称名フリガナ-姓", max_length=50,  blank=True, null=True)
    tsuushoumeifurigana_mei = models.CharField(
        "通称名フリガナ-名", max_length=50,  blank=True, null=True)
    eiji_sei = models.CharField("英字-姓", max_length=50, blank=True, null=True)
    eiji_mei = models.CharField("英字-名", max_length=50, blank=True, null=True)
    seinengappi = models.DateField("生年月日", blank=True, null=True)
    SEX_CHOICES = (("0", ""), ("1", "男性"), ("2", "女性"), ("9", "その他"))
    seibetsu = models.CharField("性別", choices=SEX_CHOICES, max_length=1)
    gakui = models.CharField("学位", max_length=50,  blank=True, null=True)
    gakuishutokunengappi = models.CharField(
        "学位取得年月日", max_length=50, blank=True, null=True)
    bukyokumei = models.CharField("部局名", max_length=50)
    shokumei = models.CharField("職位", max_length=50)
    mailaddress1 = models.EmailField("メールアドレス1", blank=True, null=True)
    mailaddress2 = models.EmailField("メールアドレス2", blank=True, null=True)
    kakenhiouboshikaku = models.CharField("科研費応募資格", max_length=1)
    shutarukenkyuukikan = models.CharField("主たる研究機関", max_length=1)
    bukyokuchakuninbi = models.DateField("部局着任日", blank=True, null=True)
    bukyokutaininbi = models.DateField("部局退任日", blank=True, null=True)
    # 各種氏名を連結したフルネーム
    kanjishimei = models.CharField("研究者氏名", max_length=100)
    kanashimei = models.CharField("フリガナ", max_length=100)
    tsuushoumei = models.CharField(
        "通称名", max_length=100,  blank=True, null=True)
    tsuushoumei_kana = models.CharField(
        "通称名フリガナ", max_length=50,  blank=True, null=True)
    eijishimei = models.CharField(
        "英字氏名", max_length=100, blank=True, null=True)

    def age(self):
        today = date.today()
        age = today.year - self.seinengappi.year
        if (today.month, today.day) < (self.seinengappi.month, self.seinengappi.day):
            age -= 1
        return age

    def __str__(self):
        return self.eradcode


class Application(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "e-Rad応募データ"
    kakushu_no = models.CharField("各種No", max_length=20)
    kadai_id = models.CharField("課題ID", max_length=20)
    oubo_saitaku_bangou = models.CharField("応募／採択番号", max_length=20)
    nendo = models.IntegerField("年度")
    seido_code = models.CharField("制度コード", max_length=7)
    seidomei = models.CharField("制度名", max_length=200)
    jigyoumei = models.CharField("事業名", max_length=200)
    koubogroupmei = models.CharField("公募グループ名", max_length=200)
    koubo_nendo = models.IntegerField("公募年度")
    koubomei = models.CharField("公募名", max_length=200)
    kadaimei = models.CharField("研究開発課題名", max_length=200)
    kaishi_nendo = models.IntegerField("研究期間開始年度")
    shuuryou_nendo = models.IntegerField("研究期間終了年度")
    STATUS_CHOICE = (("1", "応募中"), ("2", "応募済"), ("3", "審査中"), ("4", "審査済"),
                     ("5", "採択"), ("6", "不受理"), ("7", "取下げ"),
                     ("8", "不採択（足切り）"), ("9", "不採択"))
    status = models.CharField("ステータス", max_length=1, choices=STATUS_CHOICE)
    eradcode = models.CharField("研究者番号", max_length=8)
    shimeikanji_sei = models.CharField("氏名漢字（姓）", max_length=50)
    shimeikanji_mei = models.CharField("氏名漢字（名）", max_length=50)
    kenkyuukikanmei = models.CharField("研究機関名", max_length=50)
    bukyokumei = models.CharField("部局名", max_length=50, blank=True, null=True)
    yakushoku = models.CharField("役職", max_length=50, blank=True, null=True)

    def __str__(self):
        return self.kakushu_no

src/grant/models.py
from django.db import models
from crm.lib.models import Person


class Project(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "課題名"
    nendo = models.IntegerField("年度")
    kadaimei = models.CharField("課題名", max_length=200)
    KUBUN_CHOICES = (("1", "新規"), ("2", "継続"))
    kubun = models.CharField("区分", max_length=1, choices=KUBUN_CHOICES)
    JUDGEMENT_CHOICES = (("1", "採択"), ("2", "不採択"), ("3", "追加採択"))
    saihi = models.CharField("採否", max_length=1, choices=JUDGEMENT_CHOICES)
    kiboukenkyuuhi = models.IntegerField("希望研究費")
    haibunkingaku = models.IntegerField("配分金額")
    bikou = models.CharField("備考", max_length=200)

    def __str__(self):
        return self.kadaimei


class Member(Person):
    class Meta:
        verbose_name = verbose_name_plural = "申請者"
    project = models.ForeignKey(Project, on_delete=models.PROTECT)
    nenrei = models.IntegerField("年齢")
    SEX_CHOICES = (("0", ""), ("1", "男性"), ("2", "女性"), ("9", "その他"))
    seibetsu = models.CharField("性別", choices=SEX_CHOICES, max_length=1)
    ROLE_CHOICES = (("1", "代表"), ("2", "分担"), ("9", "その他"))
    role = models.CharField("役割", max_length=1, choices=ROLE_CHOICES)
    AFF_CHOICES = (("1", "新潟大学"), ("9", "その他"))
    affiliation = models.CharField(
        "所属機関", max_length=1, choices=AFF_CHOICES, blank=True, null=True)

    def __str__(self):
        return self.eradcode

src/work/models.py
from django.db import models


class Keyword(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "キーワード"
    # keyword_id = models.IntegerField("キーワードID", primary_key=True)
    keyword = models.CharField("キーワード", max_length=255)
    researcher_count = models.IntegerField("使用研究者数")
    cumcount = models.IntegerField("のべ使用回数")

    def __str__(self):
        return self.keyword


class Work(models.Model):
    class Meta:
        verbose_name = verbose_name_plural = "研究課題"
    awardnumber = models.CharField("課題番号", max_length=255)
    title = models.CharField("課題名", max_length=255)
    startfiscalyear = models.IntegerField("研究開始年度")
    role = models.CharField("役割", max_length=255)
    category_name = models.CharField("研究種目", max_length=255)
    eradcode = models.CharField("研究者番号", max_length=8)
    fullname = models.CharField("氏名", max_length=255)
    institution = models.CharField("部局名", max_length=255)
    department = models.CharField("部局名", max_length=255)
    jobtitle = models.CharField("職名", max_length=255)
    keywords = models.ManyToManyField(Keyword)

    def __str__(self):
        return self.eradcode

src/erad/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django import forms
from django.urls import reverse


class ResearcherSearchForm(forms.Form):
    shimei = forms.CharField(label="氏名", required=False)
    shozoku = forms.CharField(label="所属", required=False)

    def __init__(self, *args, **kwargs):
        super(ResearcherSearchForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Row(
                Column('shimei', css_class='form-group col-md-6 mb-0'),
                Column('shozoku', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
        )
        self.helper.form_method = "GET"
        self.helper.form_action = reverse("erad:list")
        self.helper.add_input(
            Submit('', '検索', css_class='btn btn-primary'))

src/erad/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, Q
from django.views.generic import DetailView, ListView
from grant.models import Member
from nayose.models import Nayose
from attribute.models import Eligible
from event.models import Attendee
from support.models import CompetitiveFund, Kakenhi, Matching
from work.models import Keyword, Work

from .forms import ResearcherSearchForm
from .models import Application, Researcher


class ResearcherFrontView(LoginRequiredMixin, ListView):
    template_name = "erad/researcher_front.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = ResearcherSearchForm()
        return context

    def get_queryset(self):
        queryset = Researcher.objects.values("bukyokumei").annotate(cnt=Count(
            "bukyokumei")).order_by("-cnt")
        return queryset


class ResearcherListView(LoginRequiredMixin, ListView):
    paginate_by = 10000

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["shimei"] = self.request.GET.get("shimei")
        context["shozoku"] = self.request.GET.get("shozoku")
        return context

    def get_queryset(self):
        queryset = Researcher.objects.all()
        if self.request.GET.get("shimei"):
            # 検索クエリ内の空白文字を削除する
            shimei = self.request.GET.get("shimei").strip()
            table = str.maketrans({"　": "", " ": ""})
            shimei = shimei.translate(table)
            # 検索する
            queryset = queryset.filter(
                Q(kanjishimei__icontains=shimei)
                | Q(kanashimei__icontains=shimei)
                | Q(tsuushoumei__icontains=shimei)
                | Q(eijishimei__icontains=shimei)
            )
        if self.request.GET.get("shozoku"):
            shozoku = self.request.GET.get("shozoku")
            queryset = queryset.filter(bukyokumei__icontains=shozoku)
        queryset = queryset.order_by("kanashimei")
        return queryset


class ResearcherDetailView(LoginRequiredMixin, DetailView):
    model = Researcher

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get("pk")
        context["nayose"] = Nayose.objects.get(eradcode=pk)
        context["attendee_list"] = Attendee.objects.select_related().filter(
            eradcode=pk)
        context["support_kakenhi_list"] = Kakenhi.objects.filter(
            eradcode=pk).order_by("uketsukebi").reverse()
        context["support_competitivefund_list"] = CompetitiveFund.objects.filter(
            eradcode=pk).order_by("uketsukebi").reverse()
        context["support_matching_list"] = Matching.objects.filter(
            eradcode=pk).order_by("uketsukebi").reverse()
        context["eligible_list"] = Eligible.objects.select_related().filter(
            eradcode=pk).order_by("nendo").reverse()
        context["grant_member_list"] = Member.objects.select_related().filter(
            eradcode=pk).order_by("project__nendo").reverse()
        context["kakenhi_list"] = Application.objects.filter(
            eradcode=pk).filter(seido_code="S000003").order_by("nendo").reverse()
        context["erad_list"] = Application.objects.filter(
            eradcode=pk).exclude(seido_code="S000003").order_by("nendo").reverse()
        context["work_list"] = Work.objects.filter(
            eradcode=pk).order_by("-startfiscalyear")
        context["keyword_list"] = Keyword.objects.select_related().filter(
            work__eradcode=pk).annotate(count=Count("keyword")).order_by("-count")

        return context

src/erad/templates/erad/researcher_detail.html
{% extends "_base.html" %}
{% load static %}
{% load humanize %}
{% block header %}研究者情報{% endblock header %}
{% block admin_changelist %}{% url 'admin:erad_researcher_changelist' %}{% endblock admin_changelist %}

{% block contents %}
<div class="row">
    <div class="col-md-12">
        <div class="card my-3">
            <div class="card-header">
                <h3 class="card-title h5">
                    基本情報
                    {% if object.bukyokutaininbi %}
                    <span class="badge badge-warning">転出</span>
                    {% else %}
                    <span class="badge badge-info">機関所属</span>
                    {% endif %}
                </h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <dl class="row">
                            <dt class="col-md-3">氏名</dt>
                            <dd class="col-md-9">{{ object.kenkyuushashimei_sei }} {{ object.kenkyuushashimei_mei }}
                                <span class="small text-muted">{{ object.furigana_sei }}
                                    {{ object.furigana_mei }}</span>
                            </dd>
                            <dt class="col-md-3">通称名</dt>
                            <dd class="col-md-9">{{ object.tsuushoumei_sei|default:"登録なし" }}
                                {{ object.tsuushoumei_mei|default:"" }}
                                <span class="small text-muted">{{ object.tsuushoumeifurigana_sei|default:"" }}
                                    {{ object.tsuushoumeifurigana_mei|default:"" }}</span>
                            </dd>
                            <dt class="col-md-3">英字氏名</dt>
                            <dd class="col-md-9">{{ object.eiji_sei|default:"登録なし" }}
                                {{ object.eiji_mei|default:"" }}</dd>
                            <dt class="col-md-3">生年月日</dt>
                            <dd class="col-md-9">{{ object.seinengappi }}</dd>
                            <dt class="col-md-3">今日時点の年齢</dt>
                            <dd class="col-md-9">{{ object.age }} 歳</dd>
                            <dt class="col-md-3">性別</dt>
                            <dd class="col-md-9">{{ object.get_seibetsu_display }}</dd>
                            <dt class="col-md-3">部局名</dt>
                            <dd class="col-md-9">{{ object.bukyokumei }}</dd>
                            <dt class="col-md-3">職名</dt>
                            <dd class="col-md-9">{{ object.shokumei }}</dd>
                            <dt class="col-md-3">研究者番号</dt>
                            <dd class="col-md-9">{{ object.pk }}</dd>
                            <dt class="col-md-3">常勤職員番号</dt>
                            <dd class="col-md-9">{{ nayose.shokuincode|default:"登録なし" }}</dd>
                            <dt class="col-md-3">非常勤職員番号</dt>
                            <dd class="col-md-9">{{ nayose.hijoukincode|default:"登録なし" }}</a></dd>
                            <dt class="col-md-3">名寄せID</dt>
                            <dd class="col-md-9">{{ nayose.pk|default:"登録なし" }}</a>
                            </dd>
                        </dl>
                    </div>
                    <div class="col-md-6">
                        <dl class="row">
                            <dt class="col-md-4">学位</dt>
                            <dd class="col-md-8">{{ object.gakui|default:"登録なし" }}</dd>
                            <dt class="col-md-4">学位取得年月日</dt>
                            <dd class="col-md-8">{{ object.gakuishutokunengappi|default:"登録なし" }}</dd>
                            <dt class="col-md-4">メールアドレス1</dt>
                            <dd class="col-md-8">{{ object.mailaddress1|default:"登録なし" }}</dd>
                            <dt class="col-md-4">メールアドレス2</dt>
                            <dd class="col-md-8">{{ object.mailaddress2|default:"登録なし" }}</dd>
                            <dt class="col-md-4">科研費応募資格</dt>
                            <dd class="col-md-8">{{ object.kakenhiouboshikaku }}</dd>
                            <dt class="col-md-4">主たる研究機関</dt>
                            <dd class="col-md-8">{{ object.shutarukenkyuukikan }}</dd>
                            <dt class="col-md-4">e-Rad部局着任日</dt>
                            <dd class="col-md-8">{{ object.bukyokuchakuninbi }}</dd>
                            <dt class="col-md-4">e-Rad部局退任日</dt>
                            <dd class="col-md-8">{{ object.bukyokutaininbi|default:"登録なし" }}</dd>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<hr>
<h3 class="h5">研究キーワード</h3>
{% if keyword_list %}
{% for keyword in keyword_list %}
<a class="btn btn-outline-secondary btn-sm my-1" href="{% url 'work:detail' keyword.id %}" role="button">
    {{ keyword.keyword }}
    <span class="badge badge-pill badge-light">{{ keyword.count }}</span>
</a>
{% endfor %}
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">科研費採択課題</h3>
{% if work_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th>課題番号</th>
            <th>課題名</th>
            <th width=20%>研究種目</th>
            <th>開始年度</th>
            <th>役割</th>
        </tr>
    </thead>
    <tbody>
        {% for work in work_list %}
        <tr>
            <td>{{ work.awardnumber }}</td>
            <td>{{ work.title }}</td>
            <td>{{ work.category_name }}</td>
            <td>{{ work.startfiscalyear }}</td>
            <td>{{ work.role }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">イベント、セミナー</h3>
{% if attendee_list %}
<h6>参加状況</h6>
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th width=10%>年度</th>
            <th width=20%>開催日</th>
            <th width=30%>イベント名</th>
            <th width=30%>会場</th>
            <th width=10%></th>
        </tr>
    </thead>
    <tbody>
        {% for attendee in attendee_list %}
        <tr>
            <td>{{ attendee.event.nendo }}</td>
            <td>{{ attendee.event.kaisaibi }}</td>
            <td>{{ attendee.event.title }}</td>
            <td>{{ attendee.event.venue }}</td>
            <td> <a class="btn btn-outline-info btn-sm" href="#">
                    詳細
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">科研費申請書添削</h3>
{% if support_kakenhi_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th>年度</th>
            <th>受付日</th>
            <th>完了日</th>
            <th>研究種目</th>
            <th>主担当</th>
            <th>副担当</th>
            <th>備考</th>
            <th>採否</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for support_kakenhi in support_kakenhi_list %}
        <tr>
            <td>{{ support_kakenhi.nendo }}</td>
            <td>{{ support_kakenhi.uketsukebi }}</td>
            <td>{{ support_kakenhi.kanryoubi }}</td>
            <td>{{ support_kakenhi.shumoku }}</td>
            <td>{{ support_kakenhi.shutantou }}</td>
            <td>{{ support_kakenhi.fukutantou }}</td>
            <td>{{ support_kakenhi.bikou }}</td>
            <td>{{ support_kakenhi.get_saihi_display }}</td>
            <td> <a class="btn btn-outline-info btn-sm"
                    href="{% url 'admin:support_kakenhi_change' support_kakenhi.pk %}">
                    編集
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">競争的研究資金申請支援</h3>
{% if support_competitivefund_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th width=5%>年度</th>
            <th width=10%>受付日</th>
            <th width=5%>主担当</th>
            <th width=5%>副担当</th>
            <th width=45%>配分機関・公募名</th>
            <th width=10%>完了日</th>
            <th width=5%>採否</th>
            <th width=5%></th>
        </tr>
    </thead>
    <tbody>
        {% for support_competitivefund in support_competitivefund_list %}
        <tr>
            <td>{{ support_competitivefund.nendo }}</td>
            <td>{{ support_competitivefund.uketsukebi|date:"Y-m-d" }}</td>
            <td>{{ support_competitivefund.shutantou }}</td>
            <td>{{ support_competitivefund.fukutantou }}</td>
            <td>{{ support_competitivefund.haibunkikan }}<br>{{ support_competitivefund.koubomei }}</td>
            <td>{{ support_competitivefund.kanryoubi|date:"Y-m-d" }}</td>
            <td>{{ support_competitivefund.get_saihi_display }}</td>
            <td>
                <a class="btn btn-outline-info btn-sm"
                    href="{% url 'admin:support_competitivefund_change' support_competitivefund.pk %}">
                    編集
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">マッチング支援</h3>
{% if support_matching_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th>年度</th>
            <th>受付日</th>
            <th>完了日</th>
            <th>主担当</th>
            <th>副担当</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for support_matching in support_matching_list %}
        <tr>
            <td>{{ support_matching.nendo }}</td>
            <td>{{ support_matching.uketsukebi }}</td>
            <td>{{ support_matching.kanryoubi }}</td>
            <td>{{ support_matching.shutantou }}</td>
            <td>{{ support_matching.fukutantou }}</td>
            <td> <a class="btn btn-outline-info btn-sm"
                    href="{% url 'admin:support_matching_change' support_matching.pk %}">
                    編集
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">属性</h3>
{% if eligible_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th>年度</th>
            <th>属性</th>
            <th>備考</th>
        </tr>
    </thead>
    <tbody>
        {% for eligible in eligible_list %}
        <tr>
            <td>{{ eligible.nendo }}</td>
            <td>{{ eligible.attribute.zokusei }}</td>
            <td>{{ eligible.bikou }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">U-goグラント応募採択課題</h3>
{% if grant_member_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th width=10%>年度</th>
            <th width=10%>役割</th>
            <th width=50%>課題名</th>
            <th width=10%>継続</th>
            <th width=10%>採否</th>
            <th width=10%></th>
        </tr>
    </thead>
    <tbody>
        {% for grant_member in grant_member_list %}
        <tr>
            <td>{{ grant_member.project.nendo }}</td>
            <td>{{ grant_member.get_role_display }}</td>
            <td>{{ grant_member.project.kadaimei }}</td>
            <td>{{ grant_member.project.get_kubun_display }}</td>
            <td>{{ grant_member.project.get_saihi_display }}</td>
            <td> <a class="btn btn-outline-info btn-sm" href="">
                    詳細
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">科研費応募採択状況</h3>
{% if kakenhi_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th width=10%>年度</th>
            <th width=20%>研究種目</th>
            <th width=10%>研究期間</th>
            <th width=50%>課題名</th>
            <th width=10%>採否</th>
        </tr>
    </thead>
    <tbody>
        {% for kakenhi in kakenhi_list %}
        <tr>
            <td>{{ kakenhi.nendo }}</td>
            <td>{{ kakenhi.jigyoumei }}</td>
            <td>{{ kakenhi.kaishi_nendo }} - {{ kakenhi.shuuryou_nendo }}</td>
            <td>{{ kakenhi.kadaimei }}</td>
            <td>{{ kakenhi.get_status_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}
<hr>
<h3 class="h5">e-Rad応募採択状況</h3>
{% if erad_list %}
<table class="table table-striped table-sm">
    <thead class="thead-light">
        <tr>
            <th width=10%>年度</th>
            <th width=30%>事業名</th>
            <th width=10%>研究期間</th>
            <th width=40%>課題名</th>
            <th width=10%>採否</th>
        </tr>
    </thead>
    <tbody>
        {% for erad in erad_list %}
        <tr>
            <td>{{ erad.nendo }}</td>
            <td>{{ erad.seidomei }}<br>{{ erad.jigyoumei }}<br>{{ erad.koubogroupmei }}<br>{{ erad.koubomei }}</td>
            <td>{{ erad.kaishi_nendo }} - {{ erad.shuuryou_nendo }}</td>
            <td>{{ erad.kadaimei }}</td>
            <td>{{ erad.get_status_display }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p class="my-5">該当するデータがありません</p>
{% endif %}


{% endblock contents%}